name: Python package


on:
  pull_request:
  push:  

jobs:
  build:

    runs-on: ${{ vars.DEFAULT_RUNNER || 'ubuntu-latest' }}
    strategy:
      matrix:
        folders: [qcentroid_agent_cli]
    env:
      PYTHON_VERSION: 3.9       
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python ${{ env.PYTHON_VERSION }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ env.PYTHON_VERSION }}
      - name: Install dependencies
        working-directory: ${{ matrix.folders }}
        run: |
          python -m pip install --upgrade pip
          pip install ruff pytest
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
      - name: Lint with ruff
        working-directory: ${{ matrix.folders }}
        run: |
          # stop the build if there are Python syntax errors or undefined names
          ruff --output-format=github --select=E9,F63,F7,F82 --target-version=py39 .
          # default set of ruff rules with GitHub Annotations
          #ruff --format=github --target-version=py37 .
      - name: Test with pytest 
        working-directory: ${{ matrix.folders }}
        run: |
          if pytest; then
            echo "Tests passed in $folder"
          else
            exit_code=$?
            if [ $exit_code -eq 5 ]; then
              echo "::warning:: No tests found in $folder (warning)"
            else
              echo "::error:: Tests failed in $folder (error)"
              exit 1
            fi
          fi
